import './globals.css';
import {
  Noto_Sans,
  Bodoni_Moda,
  Cormorant_Garamond,
} from 'next/font/google';
import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { useContent } from '../../messages/useContent';
import HeaderScreenSelector from '@/components/header/headerSelector';
import Footer from '@/components/footer';

const noto = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-noto',
});

const bodoni = Bodoni_Moda({
  variable: '--font-bodoni',
  subsets: ['latin'],
});

const cormorant = Cormorant_Garamond({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-cormorant',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  const locale = useLocale();
  const { header, footer } = useContent();

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${noto.variable} ${cormorant.variable} 
        ${bodoni.variable} text-black`}
      >
        <div id="portal"></div>
        <HeaderScreenSelector headerContent={header} />
        {children}
        <Footer content={footer} />
      </body>
    </html>
  );
}
