import './globals.css';
import {
  Noto_Sans,
  Bodoni_Moda,
  Cormorant_Garamond,
} from 'next/font/google';
import { useLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { useContent } from '../../messages/useContent';
import HeaderScreenSelector from '@/components/header';
import Footer from '@/components/footer';
import ContextWrapper from '@/contexts/wrapper';
import { makeRequest } from '@/utils/query/makeRequest';

const noto = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-noto',
});

const bodoni = Bodoni_Moda({
  variable: '--font-bodoni',
  subsets: ['latin'],
});

const cormorant = Cormorant_Garamond({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-cormorant',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const locale = useLocale();
  const { header, footer } = useContent();

  if (params.locale !== locale) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body
        className={`${noto.variable} ${cormorant.variable} 
        ${bodoni.variable} relative tracking-tight text-black`}
      >
        <ContextWrapper lang={locale}>
          <div id="portal"></div>
          <HeaderScreenSelector
            headerContent={header}
            reqFunction={makeRequest}
          />
          {children}
          <Footer content={footer} />
        </ContextWrapper>
      </body>
    </html>
  );
}
